services:
  web_file:
    build: .
    container_name: arpas_backend_file
    labels:
      - "container_name=file"
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - STORAGE_BACKEND=file
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - ./uploaded_files:/app/uploaded_files
  # Database (BLOB) storage
  web_db:
    build: .
    container_name: arpas_backend_db
    labels:
      - "container_name=db"
    ports:
      - "8002:8000"
    env_file:
      - .env
    environment:
      - STORAGE_BACKEND=db
      - DATABASE_URL=sqlite:///./arpas-dev.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
  # FastAPI service
  web_minio:
    build: .
    container_name: arpas_backend_minio
    labels:
      - "container_name=minio"
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - STORAGE_BACKEND=minio
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - DATABASE_URL=${DATABASE_URL}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - ./uploaded_files:/app/uploaded_files

  # MinIO service
  minio:
    image: minio/minio:latest
    container_name: minio_arpas_storage
    labels:
      - "container_name=minio-storage"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # RESTful API Port
      - "9001:9001"  # MinIO browser console
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
  locust:
    build:
      context: .
      dockerfile: benchmarks/Dockerfile.locust
    container_name: locust_load_tester
    environment:
      - LOCUST_EXPORTER_ENABLED=1
      - LOCUST_EXPORTER_PORT=9645
    labels:
      - "container_name=locust_load_tester"
    depends_on:
      - web_file
    ports:
      - "8089:8089"
      - "9645:9645"
    volumes:
      - .:/app
    working_dir: /app/benchmarks
    command: [
      "locust",
      "-f", "locustfile.py"
    ]
  socat:
    image: alpine/socat
    container_name: socat
    command: [ "-d", "-d", "TCP-LISTEN:2375,reuseaddr,fork", "UNIX-CONNECT:/var/run/docker.sock" ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      bench_network:

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    ports:
      - "9273:9273"
    depends_on:
      - socat
    environment:
      - HOST_PROC=/host/proc
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    networks:
      bench_network:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    labels:
      - "container_name=prometheus"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"  # Prometheus web UI
    networks:
      bench_network:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    labels:
      - "container_name=grafana"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # default credentials (admin/admin)
    ports:
      - "3000:3000"  # Grafana UI is available on port 3000
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-datasource-config.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    networks:
      bench_network:
volumes:
  minio_data:
  grafana-storage:
networks:
  bench_network:
