{
 "title": "Docker Monitoring - Arpas Backend",
 "time": { "from": "2025-03-05T23:23:10.058Z", "to": "2025-03-05T23:52:11.595Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Benchmark Container-Anzahl",
   "type": "gauge",
   "description": "Gesamtzahl der Container mit dem Namen *web_**",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(docker_container_status_pid{com_docker_compose_service=~\"web_.+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory-Auslastung pro Container",
   "type": "timeseries",
   "description": "Memory-Auslastung der Container mit dem Namen *Arpas_backend_*",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(mem{name=~\"web_.+\"}) by (name) / sum(container_spec_memory_limit_bytes{name=~\"Arpas_backend_.+\"}) by (name) * 100",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "docker_container_mem_usage_percent{com_docker_compose_service=~\"web_.+\"}",
     "legendFormat": "{{com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "CPU-Auslastung pro Container",
   "type": "timeseries",
   "description": "CPU-Auslastung der Benchmark-Container",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent{com_docker_compose_service=~\"web_.+\"}",
     "legendFormat": "{{com_docker_compose_service}}"
    },
    { "legendFormat": "__auto" }
   ]
  }
 ]
}