scrape_configs:
  - job_name: 'telegraf'
    static_configs:
      - targets: ['telegraf:9273']
    scrape_interval: 1s

  - job_name: 'locust'
    metrics_path: /metrics
    static_configs:
      - targets:
          - locust-metrics-exporter:9646
    scrape_interval: 1s