{
 "title": "Locust Prometheus Monitoring Modern",
 "description": "Locust Exporter",
 "tags": [
  "locust",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Locust Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "locust_up == 1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Swarmed users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "locust_users" }
   ]
  },
  {
   "title": "Current RPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(locust_requests_current_rps)",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(locust_requests_num_requests{method=~\".+\"})"
    }
   ]
  },
  {
   "title": "Fails",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "locust_requests_fail_ratio" }
   ]
  },
  {
   "title": "Connected workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "locust_workers_count" }
   ]
  },
  {
   "title": "Failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(locust_requests_num_failures{method=~\".+\"})"
    }
   ]
  },
  {
   "title": "Aggregate Report",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(locust_requests_response_time_percentile_95{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_response_time_percentile_99{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_min_response_time{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_max_response_time{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_avg_response_time{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_median_response_time{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_num_failures{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_current_fail_per_sec{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "(sum(locust_requests_num_failures{method=~\".+\"}) by (method, name))/(sum(locust_requests_num_requests{method=~\".+\"}) by (method, name))"
    },
    {
     "expr": "sum(locust_requests_num_requests{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_avg_content_length{method=~\".+\"}) by (method, name)"
    },
    {
     "expr": "sum(locust_requests_current_rps{method=~\".+\"}) by (method, name)"
    }
   ]
  },
  {
   "title": "RPS (endpoints)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "locust_requests_current_rps{method=~\".+\"}",
     "legendFormat": "{{ method}} - {{name}}"
    }
   ]
  },
  {
   "title": "Users and Total RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "locust_users", "legendFormat": "Users" },
    {
     "expr": "avg(locust_requests_current_rps)",
     "legendFormat": "Current RPS"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Errors Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(locust_requests_current_fail_per_sec{method=~\".+\"}) by (method, name)",
     "legendFormat": "{{method}} - {{name}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(locust_errors) by (method, name, error)"
    }
   ]
  },
  { "title": "Response Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Response Times (windowed)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "locust_requests_current_response_time_percentile_50",
     "legendFormat": "P50"
    },
    {
     "expr": "max(locust_requests_current_response_time_percentile_95)",
     "legendFormat": "P90"
    },
    {
     "expr": "max(locust_requests_response_time_percentile_95)",
     "legendFormat": "P95"
    },
    { "expr": "locust_total_avg_response_time", "legendFormat": "Total Average" }
   ]
  },
  {
   "title": "Response Times (average for all requests)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(locust_requests_max_response_time{method=~\".+\"})",
     "legendFormat": "AVG MAX"
    },
    {
     "expr": "avg(locust_requests_min_response_time{method=~\".+\"})",
     "legendFormat": "AVG MIN"
    },
    {
     "expr": "avg(locust_requests_avg_response_time{method=~\".+\"})",
     "legendFormat": "AVG AVG"
    },
    {
     "expr": "avg(locust_requests_median_response_time{method=~\".+\"})",
     "legendFormat": "AVG MEDIAN"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "locust_requests_avg_response_time{method=~\".+\"}",
     "legendFormat": "{{method}} - {{name}}"
    }
   ]
  },
  {
   "title": "Median (window)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "locust_requests_median_response_time{method=~\".+\"}",
     "legendFormat": "{{method}} - {{name}}"
    }
   ]
  },
  {
   "title": "95 %ile (window)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "locust_requests_response_time_percentile_95{method=~\".+\"}",
     "legendFormat": "{{method}} - {{name}}"
    }
   ]
  },
  {
   "title": "99 %ile (window)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "locust_requests_response_time_percentile_99{method=~\".+\"}",
     "legendFormat": "{{method}} - {{name}}"
    }
   ]
  },
  {
   "title": "Workers and users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 },
   "collapsed": true,
   "panels": [
    {
     "title": "Users",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "locust_user_count", "legendFormat": "Users" }
     ]
    },
    {
     "title": "Workers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "locust_workers", "legendFormat": "Workers" }
     ]
    },
    {
     "title": "Workers Info",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "targets": [
      { "expr": "locust_workers_info", "legendFormat": "Workers" }
     ]
    }
   ]
  }
 ]
}